import { Injectable, PLATFORM_ID, inject, signal } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../environments/environment';
import type { Socket } from 'socket.io-client';
import { IdbService } from './idb.service';

export interface ChatMessage {
    id: string;
    sessionId: string;
    content: string;
    sender: 'visitor' | 'admin';
    read: boolean;
    createdAt: string;
    messageType?: 'text' | 'audio' | 'file';
    audioUrl?: string | null;
    fileUrl?: string | null;
    fileName?: string | null;
    fileType?: string | null;
    fileSize?: number | null;
    /** True when this message was generated by the AI bot */
    isBot?: boolean;
    /** Client-side only: true when this admin message arrived while the widget was closed */
    isUnread?: boolean;
    /** Client-side only: true when queued for sending while offline */
    pending?: boolean;
}

export interface ChatSession {
    id: string;
    visitorName: string;
    status: 'active' | 'closed';
    createdAt: string;
    lastActivityAt: string;
    unreadCount: number;
    visitorSessionId?: string | null;
    notes?: string | null;
    botEnabled?: boolean;
    leadId?: string | null;
}

export interface ChatSettings {
    greeting_messages: string[];
    hold_messages: string[];
    status_message: string;
}

export interface VisitorActivity {
    type: 'page' | 'event';
    label: string;
    path: string | null;
    timestamp: string;
}

const MAX_ACTIVITY = 3;
const SESSION_KEY = 'chat_session_id';
const VISITOR_NAME_KEY = 'chat_visitor_name';

@Injectable({ providedIn: 'root' })
export class ChatService {
    private readonly http = inject(HttpClient);
    private readonly platformId = inject(PLATFORM_ID);
    private readonly idb = inject(IdbService);

    private socket?: Socket;
    private socketUrl = environment.apiUrl.replace('/api/v1', '');

    // ─── Visitor state (chat widget) ─────────────────────────────────────────
    readonly visitorSessionId = signal<string | null>(null);
    readonly visitorMessages = signal<ChatMessage[]>([]);
    readonly adminIsTyping = signal(false);
    readonly sessionClosed = signal(false);
    /** True when there are messages queued offline waiting to be sent */
    readonly chatQueued = signal(false);

    // ─── Admin state ─────────────────────────────────────────────────────────
    readonly sessions = signal<ChatSession[]>([]);
    readonly activeMsgs = signal<ChatMessage[]>([]);
    readonly activeSessionId = signal<string | null>(null);
    readonly visitorTyping = signal<{ sessionId: string; isTyping: boolean } | null>(null);
    readonly unreadChatCount = signal(0);
    /** Maps visitor session ID → current page path (updated via realtime events) */
    readonly currentPageMap = signal<Record<string, string>>({});
    /** Maps visitor session ID → recent activity entries (page views + events) */
    readonly activityLog = signal<Record<string, VisitorActivity[]>>({});

    // ─── Settings ─────────────────────────────────────────────────────────────
    readonly settings = signal<ChatSettings | null>(null);

    loadSettings() {
        this.http.get<ChatSettings>(`${environment.apiUrl}/chat/settings`).subscribe({
            next: (s) => this.settings.set(s),
        });
    }

    saveSettings(key: string, value: unknown) {
        return this.http.post(`${environment.apiUrl}/chat/settings`, { key, value });
    }

    // ─── Visitor WebSocket ────────────────────────────────────────────────────

    async connectAsVisitor(visitorName: string, contact?: { email?: string; phone?: string }) {
        if (!isPlatformBrowser(this.platformId)) return;

        // Disconnect any existing socket before creating a new connection
        this.socket?.disconnect();
        this.socket = undefined;

        const sessionId = sessionStorage.getItem(SESSION_KEY);

        // Show cached messages immediately (stale-while-revalidate) before socket connects
        if (sessionId) {
            const cached = await this.idb.getAllByIndex<ChatMessage>('chat_messages', 'sessionId', sessionId);
            if (cached.length) {
                const confirmed = cached.filter(m => !m.pending);
                const pending = cached.filter(m => m.pending);
                this.visitorMessages.set([...confirmed, ...pending].map(m => ({ ...m, isUnread: false })));
                if (pending.length) this.chatQueued.set(true);
            }
        }

        const { io } = await import('socket.io-client');

        this.socket = io(`${this.socketUrl}/chat`, {
            transports: ['websocket', 'polling'],
        });

        this.socket.on('connect', async () => {
            const visitorSessionId = sessionStorage.getItem('vst_sid') ?? undefined;
            this.socket!.emit(
                'visitor:join',
                {
                    visitorName,
                    sessionId: sessionId ?? undefined,
                    visitorSessionId,
                    contactEmail: contact?.email,
                    contactPhone: contact?.phone,
                },
                async (res: { sessionId: string; messages: ChatMessage[] }) => {
                    sessionStorage.setItem(SESSION_KEY, res.sessionId);
                    sessionStorage.setItem(VISITOR_NAME_KEY, visitorName);
                    this.visitorSessionId.set(res.sessionId);

                    // Persist server history to IDB
                    if (res.messages.length) {
                        await this.idb.putMany<ChatMessage>('chat_messages', res.messages);
                    }

                    // Fetch IDB pending messages for this session (survive page refresh)
                    const allCached = await this.idb.getAllByIndex<ChatMessage>('chat_messages', 'sessionId', res.sessionId);
                    const pendingMsgs = allCached.filter(m => m.pending);

                    // Show server history + any still-pending messages
                    this.visitorMessages.set([
                        ...res.messages.map(m => ({ ...m, isUnread: false })),
                        ...pendingMsgs,
                    ]);

                    // Flush pending messages to the server
                    let remaining = pendingMsgs.length;
                    if (remaining === 0) {
                        this.chatQueued.set(false);
                    } else {
                        for (const pendingMsg of pendingMsgs) {
                            this.socket!.emit('visitor:message', { sessionId: res.sessionId, content: pendingMsg.content }, async (msg: ChatMessage) => {
                                if (msg) {
                                    this.visitorMessages.update(msgs => [...msgs.filter(m => m.id !== pendingMsg.id), msg]);
                                    await this.idb.delete('chat_messages', pendingMsg.id);
                                    await this.idb.put<ChatMessage>('chat_messages', msg);
                                }
                                if (--remaining === 0) this.chatQueued.set(false);
                            });
                        }
                    }
                },
            );
        });

        this.socket.on('message:new', (msg: ChatMessage) => {
            // New admin messages are unread until the widget is opened
            this.visitorMessages.update(m => [...m, { ...msg, isUnread: msg.sender === 'admin' }]);
            this.idb.put<ChatMessage>('chat_messages', msg);
        });

        this.socket.on('admin:typing', (data: { isTyping: boolean }) => {
            this.adminIsTyping.set(data.isTyping);
        });

        this.socket.on('session:closed', () => {
            this.sessionClosed.set(true);
            // Clear stored session so a refresh starts fresh
            sessionStorage.removeItem(SESSION_KEY);
            sessionStorage.removeItem(VISITOR_NAME_KEY);
        });

        this.socket.on('session:deleted', () => {
            this.sessionClosed.set(true);
            sessionStorage.removeItem(SESSION_KEY);
            sessionStorage.removeItem(VISITOR_NAME_KEY);
        });
    }

    sendVisitorMessage(content: string) {
        const sessionId = this.visitorSessionId();
        if (!sessionId) return;

        // Always show the message immediately as pending — socket.io may still
        // report connected:true for seconds after going offline (heartbeat delay),
        // so we can't rely on the connected flag to decide whether to show it.
        const localId = `local_${Date.now()}`;
        const localMsg: ChatMessage = {
            id: localId,
            sessionId,
            content,
            sender: 'visitor',
            read: false,
            createdAt: new Date().toISOString(),
            messageType: 'text',
            pending: true,
        };
        this.visitorMessages.update(m => [...m, localMsg]);

        if (!this.socket?.connected) {
            this.idb.put<ChatMessage>('chat_messages', localMsg);
            this.chatQueued.set(true);
            return;
        }

        this.socket.emit('visitor:message', { sessionId, content }, (msg: ChatMessage) => {
            if (msg) {
                // Replace the optimistic pending msg with the server-confirmed one
                this.visitorMessages.update(msgs => [...msgs.filter(m => m.id !== localId), msg]);
                this.idb.put<ChatMessage>('chat_messages', msg);
            }
        });
    }

    sendVisitorAudioMessage(audioUrl: string) {
        const sessionId = this.visitorSessionId();
        if (!sessionId) return;
        this.socket?.emit('visitor:audio_message', { sessionId, audioUrl }, (msg: ChatMessage) => {
            if (msg) this.visitorMessages.update(m => [...m, msg]);
        });
    }

    uploadChatAudio(blob: Blob): Observable<{ url: string }> {
        const form = new FormData();
        form.append('file', blob, 'audio.webm');
        const sessionId = this.visitorSessionId();
        const url = sessionId
            ? `${environment.apiUrl}/chat/audio?sessionId=${sessionId}`
            : `${environment.apiUrl}/chat/audio`;
        return this.http.post<{ url: string }>(url, form);
    }

    sendVisitorTyping(isTyping: boolean) {
        const sessionId = this.visitorSessionId();
        if (!sessionId) return;
        this.socket?.emit('visitor:typing', { sessionId, isTyping });
    }

    /** Clear unread flags on all visitor messages (called when widget opens) */
    markAllVisitorMsgsRead() {
        this.visitorMessages.update(msgs => msgs.map(m => ({ ...m, isUnread: false })));
    }

    getStoredSession(): { sessionId: string | null; visitorName: string | null } {
        if (!isPlatformBrowser(this.platformId)) return { sessionId: null, visitorName: null };
        return {
            sessionId: sessionStorage.getItem(SESSION_KEY),
            visitorName: sessionStorage.getItem(VISITOR_NAME_KEY),
        };
    }

    resetVisitorSession() {
        const sessionId = this.visitorSessionId();
        if (sessionId) {
            // Clear IDB messages for this session (including any pending ones)
            this.idb.getAllByIndex<ChatMessage>('chat_messages', 'sessionId', sessionId)
                .then(msgs => Promise.all(msgs.map(m => this.idb.delete('chat_messages', m.id))));
        }
        this.socket?.disconnect();
        this.socket = undefined;
        sessionStorage.removeItem(SESSION_KEY);
        sessionStorage.removeItem(VISITOR_NAME_KEY);
        this.visitorSessionId.set(null);
        this.visitorMessages.set([]);
        this.adminIsTyping.set(false);
        this.sessionClosed.set(false);
        this.chatQueued.set(false);
    }

    disconnectVisitor() {
        this.socket?.disconnect();
    }

    // ─── Admin WebSocket ──────────────────────────────────────────────────────

    private adminConnected = false;

    async connectAsAdmin() {
        if (!isPlatformBrowser(this.platformId) || this.adminConnected) return;
        this.adminConnected = true;
        const { io } = await import('socket.io-client');

        this.socket = io(`${this.socketUrl}/chat`, {
            transports: ['websocket', 'polling'],
        });

        this.socket.on('connect', () => {
            this.socket!.emit('admin:join', null, (sessions: ChatSession[]) => {
                this.sessions.set(sessions);
                this.updateUnreadCount(sessions);
            });
        });

        this.socket.on('sessions:update', (sessions: ChatSession[]) => {
            // If admin is currently viewing a session, keep its unread count at 0
            // so the counter doesn't flicker after auto-marking messages as read
            const activeId = this.activeSessionId();
            const adjusted = activeId
                ? sessions.map(s => s.id === activeId ? { ...s, unreadCount: 0 } : s)
                : sessions;
            this.sessions.set(adjusted);
            this.updateUnreadCount(adjusted);
        });

        this.socket.on('message:new', (msg: ChatMessage) => {
            // Clear the typing indicator before appending the new message
            if (msg.sender === 'visitor') {
                this.visitorTyping.set(null);
            }
            if (msg.sessionId === this.activeSessionId()) {
                this.activeMsgs.update(m => [...m, msg]);
                // Auto-mark as read — admin is actively viewing this session
                if (msg.sender === 'visitor') {
                    this.markSessionReadHttp(msg.sessionId).subscribe();
                }
            }
        });

        this.socket.on('visitor:typing', (data: { sessionId: string; isTyping: boolean }) => {
            this.visitorTyping.set(data);
        });

        this.socket.on('session:deleted', ({ sessionId }: { sessionId: string }) => {
            this.sessions.update(s => s.filter(sess => sess.id !== sessionId));
            if (this.activeSessionId() === sessionId) {
                this.activeSessionId.set(null);
                this.activeMsgs.set([]);
            }
        });
    }

    selectSession(sessionId: string) {
        this.activeSessionId.set(sessionId);
        this.socket?.emit('admin:select_session', { sessionId }, (msgs: ChatMessage[]) => {
            this.activeMsgs.set(msgs);
        });
    }

    sendAdminMessage(sessionId: string, content: string) {
        const localId = `local_${Date.now()}`;
        const localMsg: ChatMessage = {
            id: localId,
            sessionId,
            content,
            sender: 'admin',
            read: true,
            createdAt: new Date().toISOString(),
            messageType: 'text',
            pending: true,
        };
        this.activeMsgs.update(m => [...m, localMsg]);

        this.socket?.emit('admin:message', { sessionId, content }, (msg: ChatMessage) => {
            if (msg) {
                this.activeMsgs.update(msgs => [...msgs.filter(m => m.id !== localId), msg]);
            }
        });
    }

    sendAdminAudioMessage(sessionId: string, audioUrl: string) {
        this.socket?.emit('admin:audio_message', { sessionId, audioUrl }, (msg: ChatMessage) => {
            if (msg) this.activeMsgs.update(m => [...m, msg]);
        });
    }

    uploadAdminFiles(files: File[], sessionId: string): Observable<{ url: string; name: string; type: string; size: number }[]> {
        const form = new FormData();
        for (const f of files) form.append('files', f, f.name);
        return this.http.post<{ url: string; name: string; type: string; size: number }[]>(
            `${environment.apiUrl}/chat/admin/files?sessionId=${encodeURIComponent(sessionId)}`,
            form,
        );
    }

    sendAdminFileMessage(sessionId: string, fileUrl: string, fileName: string, fileType: string, fileSize: number, caption = '') {
        this.socket?.emit('admin:file_message', { sessionId, fileUrl, fileName, fileType, fileSize, caption }, (msg: ChatMessage) => {
            if (msg) this.activeMsgs.update(m => [...m, msg]);
        });
    }

    sendAdminTyping(sessionId: string, isTyping: boolean) {
        this.socket?.emit('admin:typing', { sessionId, isTyping });
    }

    closeSession(sessionId: string) {
        this.socket?.emit('admin:close_session', { sessionId });
    }

    deleteSession(sessionId: string) {
        return this.http.delete(`${environment.apiUrl}/chat/sessions/${sessionId}`);
    }

    markSessionReadHttp(sessionId: string) {
        return this.http.post(`${environment.apiUrl}/chat/sessions/${sessionId}/read`, {});
    }

    updateSessionNotes(sessionId: string, notes: string) {
        return this.http.post(`${environment.apiUrl}/chat/sessions/${sessionId}/notes`, { notes });
    }

    toggleSessionBot(sessionId: string, enabled: boolean) {
        this.socket?.emit('admin:toggle_bot', { sessionId, enabled });
        this.sessions.update(list =>
            list.map(s => s.id === sessionId ? { ...s, botEnabled: enabled } : s)
        );
    }

    disconnectAdmin() {
        this.adminConnected = false;
        this.socket?.disconnect();
    }

    updateCurrentPage(visitorSessionId: string, path: string, timestamp: string) {
        const normalizedPath = path || '/';
        this.currentPageMap.update(m => ({ ...m, [visitorSessionId]: normalizedPath }));
        this._pushActivity(visitorSessionId, { type: 'page', label: normalizedPath, path: normalizedPath, timestamp });
    }

    logVisitorEvent(visitorSessionId: string, eventName: string, path: string | null, timestamp: string) {
        this._pushActivity(visitorSessionId, { type: 'event', label: eventName, path, timestamp });
    }

    clearCurrentPage(visitorSessionId: string) {
        this.currentPageMap.update(m => {
            const copy = { ...m };
            delete copy[visitorSessionId];
            return copy;
        });
    }

    private _pushActivity(visitorSessionId: string, entry: VisitorActivity) {
        this.activityLog.update(log => {
            const existing = log[visitorSessionId] ?? [];
            const updated = [entry, ...existing].slice(0, MAX_ACTIVITY);
            return { ...log, [visitorSessionId]: updated };
        });
    }

    private updateUnreadCount(sessions: ChatSession[]) {
        const count = sessions.reduce((sum, s) => sum + (s.unreadCount ?? 0), 0);
        this.unreadChatCount.set(count);
    }
}
